version: "3.8"

services:
  app:
    image: node:14.17.1-alpine3.13
    container_name: peteco
    restart: always
    command: npm run dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres
    container_name: peteco_db
    restart: always
    volumes:
      - ./.docker/pg/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=peteco
      - POSTGRES_DB=peteco
    network_mode: host
